# CMake generated Testfile for 
# Source directory: /media/shong/IntHard1/Projects/4DShapeAnalysis/Code/SPTSkeleton/CMRepReg/deformetrica/cmrep/testing
# Build directory: /media/shong/IntHard1/Projects/4DShapeAnalysis/Code/SPTSkeleton/CMRepReg/deformetrica/bin_cmrep/testing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(TestSparseSolver "/media/shong/IntHard1/Projects/4DShapeAnalysis/Code/SPTSkeleton/CMRepReg/deformetrica/bin_cmrep/cmrep_test" "SPARSE")
add_test(TestBruteNoImage "/media/shong/IntHard1/Projects/4DShapeAnalysis/Code/SPTSkeleton/CMRepReg/deformetrica/bin_cmrep/cmrep_test" "DERIV1" "/media/shong/IntHard1/Projects/4DShapeAnalysis/Code/SPTSkeleton/CMRepReg/deformetrica/cmrep/testing/t001_subject_brute.cmrep")
add_test(TestBruteWithImage "/media/shong/IntHard1/Projects/4DShapeAnalysis/Code/SPTSkeleton/CMRepReg/deformetrica/bin_cmrep/cmrep_test" "DERIV2" "/media/shong/IntHard1/Projects/4DShapeAnalysis/Code/SPTSkeleton/CMRepReg/deformetrica/cmrep/testing/t001_subject_brute.cmrep" "/media/shong/IntHard1/Projects/4DShapeAnalysis/Code/SPTSkeleton/CMRepReg/deformetrica/cmrep/testing/t001_img_binary.nii.gz" "/media/shong/IntHard1/Projects/4DShapeAnalysis/Code/SPTSkeleton/CMRepReg/deformetrica/bin_cmrep/testing/t001_param.txt")
add_test(TestPDENoImage "/media/shong/IntHard1/Projects/4DShapeAnalysis/Code/SPTSkeleton/CMRepReg/deformetrica/bin_cmrep/cmrep_test" "DERIV1" "/media/shong/IntHard1/Projects/4DShapeAnalysis/Code/SPTSkeleton/CMRepReg/deformetrica/cmrep/testing/caudate_pde_model.cmrep")
add_test(TestPDEWithImage "/media/shong/IntHard1/Projects/4DShapeAnalysis/Code/SPTSkeleton/CMRepReg/deformetrica/bin_cmrep/cmrep_test" "DERIV2" "/media/shong/IntHard1/Projects/4DShapeAnalysis/Code/SPTSkeleton/CMRepReg/deformetrica/cmrep/testing/caudate_pde_model.cmrep" "/media/shong/IntHard1/Projects/4DShapeAnalysis/Code/SPTSkeleton/CMRepReg/deformetrica/cmrep/testing/caudate_target.nii.gz")
add_test(ShootingRegression "/media/shong/IntHard1/Projects/4DShapeAnalysis/Code/SPTSkeleton/CMRepReg/deformetrica/bin_cmrep/shooting_test" "/media/shong/IntHard1/Projects/4DShapeAnalysis/Code/SPTSkeleton/CMRepReg/deformetrica/cmrep/testing/shooting/shoot_regression.mat")
add_test(ShootingA "/media/shong/IntHard1/Projects/4DShapeAnalysis/Code/SPTSkeleton/CMRepReg/deformetrica/bin_cmrep/lmshoot" "-m" "/media/shong/IntHard1/Projects/4DShapeAnalysis/Code/SPTSkeleton/CMRepReg/deformetrica/cmrep/testing/shooting/shooting_test_2d_template.vtk" "/media/shong/IntHard1/Projects/4DShapeAnalysis/Code/SPTSkeleton/CMRepReg/deformetrica/cmrep/testing/shooting/shooting_test_2d_target.vtk" "-o" "/media/shong/IntHard1/Projects/4DShapeAnalysis/Code/SPTSkeleton/CMRepReg/deformetrica/bin_cmrep/res.vtk" "-s" "0.2" "-l" "20" "-d" "2" "-a" "A" "-i" "20")
add_test(ShootingG "/media/shong/IntHard1/Projects/4DShapeAnalysis/Code/SPTSkeleton/CMRepReg/deformetrica/bin_cmrep/lmshoot" "-m" "/media/shong/IntHard1/Projects/4DShapeAnalysis/Code/SPTSkeleton/CMRepReg/deformetrica/cmrep/testing/shooting/shooting_test_2d_template.vtk" "/media/shong/IntHard1/Projects/4DShapeAnalysis/Code/SPTSkeleton/CMRepReg/deformetrica/cmrep/testing/shooting/shooting_test_2d_target.vtk" "-o" "/media/shong/IntHard1/Projects/4DShapeAnalysis/Code/SPTSkeleton/CMRepReg/deformetrica/bin_cmrep/res.vtk" "-s" "0.2" "-l" "20" "-d" "2" "-a" "G" "-i" "20")
